<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// english.inc
//
// English language strings

$lang = array
(
   "NOREP" => "No repository given",

   "DIFFREVS" => "Diff between revs",
   "AND" => "and",
   "REV" => "Rev",
   "LINE" => "Line",
   "SHOWALL" => "Show entire file",
   "SHOWCOMPACT" => "Only display areas with differences",
   
   "DIFFPREV" => "Diff with Previous",
   
   "GOHEAD" => "Go to head revision",
   "LASTMOD" => "Last modification",
   "LOGMSG" => "Log message",
   "SHOWCHANGED" => "Show changed files",
   "HIDECHANGED" => "Hide changed files",
   "NEWFILES" => "New Files",
   "CHANGEDFILES" => "Modified files",
   "DELETEDFILES" => "Deleted files",
   "VIEWLOG" => "View&nbsp;Log",
   "PATH" => "Path",
   "AUTHOR" => "Author",
   "LOG" => "Log",
   
   "PREV" => "Prev",
   "NEXT" => "Next",
   "SHOWALL" => "Show All",
   
   "BADCMD" => "Error running this command",
   "RETURNED" => "Returned"
);