<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// polish.inc
//
// Polish language strings in utf-8 encoding
// for /trunk version 31-Aug-2004

$lang["LOG"] = "Dziennik zmian";
$lang["DIFF"] = "Różnice";

$lang["NOREP"] = "Nie podano żadnego repozytorium";
$lang["NOPATH"] = "Nie odnaleziono ścieżki";
$lang["SUPPLYREP"] = "Proszę ustawić ścieżkę do repozytoriów w include/config.inc za pomocą \$config->parentPath lub \$config->addRepository<p>Aby uzyskać więcej szczegółów zapoznaj się z podręcznikiem instalacyjnym";

$lang["DIFFREVS"] = "Różnice pomiędzy wersjami";
$lang["AND"] = "i";
$lang["REV"] = "Wersja";
$lang["LINE"] = "Linia";
$lang["SHOWENTIREFILE"] = "Pokaż cały plik";
$lang["SHOWCOMPACT"] = "Pokaż tylko fragmęty pliku w których zaszły zmiany";

$lang["DIFFPREV"] = "Różnice pomiędzy poprzednią wersją";
$lang["BLAME"] = "Wkład poszczególnych osób";

$lang["REVINFO"] = "Informacje o wersji";
$lang["GOYOUNGEST"] = "Przejdź do najnowszej wersji";
$lang["LASTMOD"] = "Ostatnia zmiana";
$lang["LOGMSG"] = "Wpis z dziennika zmian";
$lang["CHANGES"] = "Zmiany";
$lang["SHOWCHANGED"] = "Pokaż zmienione pliki";
$lang["HIDECHANGED"] = "Ukryj zmienione pliki";
$lang["NEWFILES"] = "Nowe pliki";
$lang["CHANGEDFILES"] = "Zmienione pliki";
$lang["DELETEDFILES"] = "Usunięte pliki";
$lang["VIEWLOG"] = "Podgląd&nbsp;Dziennika&nbsp;zmian";
$lang["PATH"] = "Ścieżka";
$lang["AUTHOR"] = "Autor";
$lang["AGE"] = "Wiek";
$lang["LOG"] = "Dziennik&nbsp;zmian";
$lang["CURDIR"] = "Aktualny katalog";
$lang["TARBALL"] = "Archiwum tar";

$lang["PREV"] = "Poprzednia strona";
$lang["NEXT"] = "Następna strona";
$lang["SHOWALL"] = "Pokaż wszyskie";

$lang["BADCMD"] = "Blad podczas wykonywania polecenia";

$lang["POWERED"] = "Powered by <a href=\"http://websvn.tigris.org/\">WebSVN</a>";
$lang["PROJECTS"] = "Projekty&nbsp;Subversion";
$lang["SERVER"] = "Serwer Subversion";

$lang["SEARCHLOG"] = "Przeszukiwanie dzinnika zmian";
$lang["CLEARLOG"] = "Wyczyść aktualne rezulaty wyszukiwania";
$lang["MORERESULTS"] = "Znajdź więcej dopasowań...";
$lang["NORESULTS"] = "Żaden wpis w dzinniku zmian nie pasuje do poszukiwanego wyrażenia";
$lang["NOMORERESULTS"] = "Nie ma już więcej wpisów pasujących do zadanych kryterów";

$lang["RSSFEEDTITLE"] = "WebSVN RSS feed"; 
$lang["FILESMODIFIED"] = "zmienione plik(i)"; 
$lang["RSSFEED"] = "RSS feed"; 

$lang["LINENO"] = "Linia Nr.";
$lang["BLAMEFOR"] = "Wkład poszczególnych osób dla wersji";

$lang["YEARS"] = "lat";
$lang["MONTHS"] = "miesięcy";
$lang["WEEKS"] = "tygodni";
$lang["DAYS"] = "dni";
$lang["HOURS"] = "godzin";
$lang["MINUTES"] = "minut";

$lang["GO"] = "Przejdź";

$lang["COMPAREPATHS"] = "Porównanie scieżek";
$lang["COMPAREREVS"] = "Porównanie wersji";
//untraslated string
$lang["PROPCHANGES"] = "Property changes :";
$lang["CONVFROM"] = "Poniższe zestawienie pokazuje zmiany jakie należy dokonać, aby zmienić repozytoria o ścieżce";
$lang["TO"] = "na";
$lang["REVCOMP"] = "Odwrotne porównanie";

// The following are defined by some languages to stop unwanted line splitting
// in the template files. 

$lang["NOBR"] = "";
$lang["ENDNOBR"] = "";

// $lang["NOBR"] = "<nobr>";
// $lang["ENDNOBR"] = "</nobr>";
