<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// spanish.inc
//
// Spanish language strings

// The language name is displayed in the drop down box.  It MUST be encoded as Unicode (no HTML entities).
$lang["LANGUAGENAME"] = "Spanish";

$lang["LOG"] = "Log";
$lang["DIFF"] = "Diff";

$lang["NOREP"] = "No se especific&oacute; un repositorio";
$lang["NOPATH"] = "Ruta no encontrada";
$lang["SUPPLYREP"] = "Por Favor, configure una ruta a un repositorio en include/config.inc usando \$config->parentPath o \$config->addRepository<p>Verifique la gu&iacute;a de instalaci&oacute;n para mas detalles";

$lang["DIFFREVS"] = "Diff entre versiones";
$lang["AND"] = "y";
$lang["REV"] = "Rev";
$lang["LINE"] = "L&iacute;nea";
$lang["SHOWENTIREFILE"] = "Mostrar el archivo completo";
$lang["SHOWCOMPACT"] = "Solo mostrar &aacute;reas con diferencias";

$lang["DIFFPREV"] = "Comparar con el anterior";
$lang["BLAME"] = "Autor&iacute;a";

$lang["REVINFO"] = "Informaci&oacute;n sobre la revisi&oacute;n";
$lang["GOYOUNGEST"] = "Ir a la &uacute;ltima revisi&oacute;n";
$lang["LASTMOD"] = "Ultima modificaci&oacute;n";
$lang["LOGMSG"] = "Mensaje de Log";
$lang["CHANGES"] = "Cambios";
$lang["SHOWCHANGED"] = "Mostrar archivos modificados";
$lang["HIDECHANGED"] = "Ocultar archivos modificados";
$lang["NEWFILES"] = "Archivos Nuevos";
$lang["CHANGEDFILES"] = "Archivos modificados";
$lang["DELETEDFILES"] = "Archivos borrados";
$lang["VIEWLOG"] = "Ver&nbsp;Log";
$lang["PATH"] = "Ruta";
$lang["AUTHOR"] = "Autor";
$lang["AGE"] = "Antig&#252;edad";
$lang["LOG"] = "Log";
$lang["CURDIR"] = "Directorio Actual";
$lang["TARBALL"] = "Tarball";

$lang["PREV"] = "Ant";
$lang["NEXT"] = "Sig";
$lang["SHOWALL"] = "Mostrar todo";

$lang["BADCMD"] = "Error ejecutando ese comando";

$lang["POWERED"] = "Powered by <a href=\"http://websvn.tigris.org/\">WebSVN</a>";
$lang["PROJECTS"] = "Proyectos de&nbsp;Subversion";
$lang["SERVER"] = "Servidor de&nbsp;Subversion";

$lang["SEARCHLOG"] = "Buscar en el log";
$lang["CLEARLOG"] = "Limpiar la b&uacute;squeda actual";
$lang["MORERESULTS"] = "Buscar mas coincidencias";
$lang["NORESULTS"] = "Ning&uacute;n log coincide con su b&uacute;squeda";
$lang["NOMORERESULTS"] = "No hay mas logs que coincidan con su b&uacute;squeda";

$lang["RSSFEEDTITLE"] = "WebSVN RSS feed"; 
$lang["FILESMODIFIED"] = "Archivo(s) modificados"; 
$lang["RSSFEED"] = "RSS feed"; 

$lang["LINENO"] = "L&iacute;nea Nro.";
$lang["BLAMEFOR"] = "Informaci&oacute;n de culpa para rev";

$lang["YEARS"] = "A&ntilde;os";
$lang["MONTHS"] = "meses";
$lang["WEEKS"] = "semanas";
$lang["DAYS"] = "d&iacute;as";
$lang["HOURS"] = "horas";
$lang["MINUTES"] = "minutos";

$lang["GO"] = "Ir";

$lang["PATHCOMPARISON"] = "Comparaci&oacute;n de rutas";
$lang["COMPAREPATHS"] = "Comparar Rutas";
$lang["COMPAREREVS"] = "Comparar Revisiones";
$lang["PROPCHANGES"] = "Cambios de propiedades :";
$lang["CONVFROM"] = "Esta Comparaci&oacute;n muestra los cambios necesarios para convertir la ruta";
$lang["TO"] = "a";
$lang["REVCOMP"] = "Revertir comparaci&oacute;n";
$lang["COMPPATH"] = "Comparar Ruta:";
$lang["WITHPATH"] = "Con Ruta:";
$lang["FILEDELETED"] = "Archivo Eliminado";
$lang["FILEADDED"] = "Archivo Nuevo";

// The following are defined by some languages to stop unwanted line splitting
// in the template files.

$lang["NOBR"] = "";
$lang["ENDNOBR"] = "";

// $lang["NOBR"] = "<nobr>";
// $lang["ENDNOBR"] = "</nobr>";
