<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// tchinese.inc
//
// Traditional Chinese language strings
// 
// Author: Yuan-Chung Hsiao <ychsiao@ychsiao.idv.tw>
//

$lang["LOG"] = "æ­·å²è¨˜é??";
$lang["DIFF"] = "æ¯”å??";

$lang["NOREP"] = "æ²’æ?‰æ?”æ??åº?";
$lang["NOPATH"] = "?‰¾ä¸å?°è·¯å¾?";
$lang["SUPPLYREP"] = "è«‹åœ¨include/config.incä¸­è¨­å®šæ?”æ??åº«ä?ç½®??? \$config->parentPath ??? \$config->addRepository<p>?›´è©³ç´°?????§å®¹è«‹è?‹å?‰è?æ?‹å??";

$lang["DIFFREVS"] = "ä¸å??????œ¬??“ç??å·®ç•°";
$lang["AND"] = "???";
$lang["REV"] = "ä¿®è????????";
$lang["LINE"] = "è¡?";
$lang["SHOWALL"] = "é¡¯ç¤ºå®??•´???æª”æ??";
$lang["SHOWCOMPACT"] = "?ªé¡¯ç¤ºä¸å?????";

$lang["DIFFPREV"] = "?????ä?????æ¬¡æ?”è??";
$lang["BLAME"] = "è­´è²¬";

$lang["REVINFO"] = "ä¿®è?????æ¬¡è??è¨?";
$lang["GOYOUNGEST"] = "??°æ???–°???ä¿®è??";
$lang["LASTMOD"] = "???å¾??›´???";
$lang["LOGMSG"] = "è¨Šæ?¯è?˜é??";
$lang["CHANGES"] = "?”¹è®?";
$lang["SHOWCHANGED"] = "é¡¯ç¤ºå·²è?Šå?•æ?”æ??";
$lang["HIDECHANGED"] = "?š±??å·²è®Šå?•æ?”æ??";
$lang["NEWFILES"] = "?–°æª”æ??";
$lang["CHANGEDFILES"] = "å·²è?Šå?•æ?”æ??";
$lang["DELETEDFILES"] = "å·²åˆª?™¤æª”æ??";
$lang["VIEWLOG"] = "??‹æ­·?²è¨˜é??";
$lang["PATH"] = "è·¯å??";
$lang["AUTHOR"] = "ä½œè??";
$lang["AGE"] = "?›´??•æ?????";
$lang["LOG"] = "æ­·å²è¨˜é??";
$lang["CURDIR"] = "?›®??ç›®???";
$lang["TARBALL"] = "Tarball ? ¼å¼?";

$lang["PREV"] = "ä¸Šä??ç­?";
$lang["NEXT"] = "ä¸‹ä??ç­?";
$lang["SHOWALL"] = "é¡¯ç¤º??¨é??";

$lang["BADCMD"] = "?Ÿ·è¡???¯èª¤";

$lang["POWERED"] = "?Ž¡?”¨ <a href=\"http://websvn.tigris.org/\">WebSVN</a>?ž¶è¨?";
$lang["PROJECTS"] = "Subversion&nbsp;å°?æ¡?";
$lang["SERVER"] = "Subversion&nbsp;Server";

$lang["SEARCHLOG"] = "??œå?‹è?˜é????§å®¹";
$lang["CLEARLOG"] = "æ¸??™¤?›®??æ?œå??";
$lang["MORERESULTS"] = "?‰¾??°æ›´å¤šç??ç¬¦å?????...";
$lang["NORESULTS"] = "?Ÿ¥è©¢ç?æ?œä¸¦æ²’æ?‰ç¬¦??????ç´????";
$lang["NOMORERESULTS"] = "æ²’æ?‰æ›´å¤šç?????ç¬¦å??ä½ ç???Ÿ¥è©?";

$lang["RSSFEEDTITLE"] = "WebSVN RSS feed"; 
$lang["FILESMODIFIED"] = "??‹æ?”æ??è®Šå??"; 
$lang["RSSFEED"] = "RSS feed"; 

$lang["LINENO"] = "è¡?";
$lang["BLAMEFOR"] = "????œ¬è­´è²¬è³?è¨?";

$lang["YEARS"] = "å¹´å??";
$lang["MONTHS"] = "??????";
$lang["WEEKS"] = "??±å??";
$lang["DAYS"] = "?—¥???";
$lang["HOURS"] = "å°æ?????";
$lang["MINUTES"] = "?????˜å??";

$lang["GO"] = "???";

$lang["COMPAREPATHS"] = "æ¯”å?è·¯å¾?";
$lang["COMPAREREVS"] = "æ¯”å?ä¿®è¨????";
$lang["PROPCHANGES"] = "?”¹è®Šå±¬??? :";
$lang["CONVFROM"] = "??™å?‹æ?”å?é¡¯ç¤ºå??????”¹è®Šè?‰æ?›è·¯å¾?";
$lang["TO"] = "???";
$lang["REVCOMP"] = "é¡›å?’æ?”å??";

// The following are defined by some languages to stop unwanted line splitting
// in the template files. 

$lang["NOBR"] = "";
$lang["ENDNOBR"] = "";
