<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// english.inc
//
// English language strings

$lang["LOG"] = "Log";
$lang["DIFF"] = "Diff";

$lang["NOREP"] = "No s'ha especificat un repositori";
$lang["NOPATH"] = "Ruta no trobada";
$lang["SUPPLYREP"] = "Per favor, configuri una ruta a un repositori a include/config.inc emprant  \$config->parentPath o \$config->addRepository<p>Verifiqui la guia de instal·lació per més detalls";

$lang["DIFFREVS"] = "Diff entre versions";
$lang["AND"] = "i";
$lang["REV"] = "Rev";
$lang["LINE"] = "Línia";
$lang["SHOWENTIREFILE"] = "Mostrar el fitxer complet";
$lang["SHOWCOMPACT"] = "Només mostrar àrees amb diferències";

$lang["DIFFPREV"] = "Comparar amb l'anterior";
$lang["BLAME"] = "Autoria";

$lang["REVINFO"] = "Informació sobre la revisió";
$lang["GOYOUNGEST"] = "Anar a la darrera revisió";
$lang["LASTMOD"] = "Darrera modificació";
$lang["LOGMSG"] = "Missatge de Log";
$lang["CHANGES"] = "Canvis";
$lang["SHOWCHANGED"] = "Mostrar fitxers modificats";
$lang["HIDECHANGED"] = "Ocultar fitxers modificats";
$lang["NEWFILES"] = "Fitxers Nous";
$lang["CHANGEDFILES"] = "Fitxers modificats";
$lang["DELETEDFILES"] = "Fitxers esborrats";
$lang["VIEWLOG"] = "Veure&nbsp;Log";
$lang["PATH"] = "Ruta";
$lang["AUTHOR"] = "Autor";
$lang["AGE"] = "Antiguitat";
$lang["LOG"] = "Log";
$lang["CURDIR"] = "Directori Actual";
$lang["TARBALL"] = "Tarball";

$lang["PREV"] = "Ant";
$lang["NEXT"] = "Sig";
$lang["SHOWALL"] = "Mostrar tot";

$lang["BADCMD"] = "Error executat aquesta comanda";

$lang["POWERED"] = "Powered by <a href=\"http://websvn.tigris.org/\">WebSVN</a>";
$lang["PROJECTS"] = "Projectos de&nbsp;Subversion de la DGTIC";
$lang["SERVER"] = "Servidor de&nbsp;Subversion de la DGTIC";

$lang["SEARCHLOG"] = "Cercar al log";
$lang["CLEARLOG"] = "Netejar la cerca actual";
$lang["MORERESULTS"] = "Cercar més coincidències";
$lang["NORESULTS"] = "Cap log coincideix amb la cerca efectuada";
$lang["NOMORERESULTS"] = "No hi ha més logs que coincideixin amb la cerca efectuada";

$lang["RSSFEEDTITLE"] = "WebSVN RSS feed"; 
$lang["FILESMODIFIED"] = "Fitxer(s) modificats"; 
$lang["RSSFEED"] = "RSS feed"; 

$lang["LINENO"] = "Línia Núm.";
$lang["BLAMEFOR"] = "Informació de responsabilitat per la rev";

$lang["YEARS"] = "Anys";
$lang["MONTHS"] = "mesos";
$lang["WEEKS"] = "setmanes";
$lang["DAYS"] = "dies";
$lang["HOURS"] = "hores";
$lang["MINUTES"] = "minuts";

$lang["GO"] = "Anar";

$lang["PATHCOMPARISON"] = "Comparació de rutes";
$lang["COMPAREPATHS"] = "Comparar Rutes";
$lang["COMPAREREVS"] = "Comparar Revisions";
$lang["PROPCHANGES"] = "Canvis de propietats :";
$lang["CONVFROM"] = "Aquesta comparació mostra els canvis necessaris per convertir la ruta";
$lang["TO"] = "a";
$lang["REVCOMP"] = "Revertir comparació";
$lang["COMPPATH"] = "Comparar Ruta:";
$lang["WITHPATH"] = "Amb Ruta:";
$lang["FILEDELETED"] = "Fitxer Eliminat";
$lang["FILEADDED"] = "Fitxer Nou";

// The following are defined by some languages to stop unwanted line splitting
// in the template files.

$lang["NOBR"] = "";
$lang["ENDNOBR"] = "";

// $lang["NOBR"] = "<nobr>";
// $lang["ENDNOBR"] = "</nobr>";
