<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// polish.inc
//
// Polish language strings in iso-8859-2 encoding

$lang["LOG"] = "Dziennik zmian";
$lang["DIFF"] = "Ró¿nice";

$lang["NOREP"] = "Nie podano ¿adnego repozytorium";
$lang["NOPATH"] = "Nie odnaleziono ¶cie¿ki";
$lang["SUPPLYREP"] = "Proszê ustawiæ ¶cie¿kê do repozytoriów w
include/config.inc za pomoc± \$config->parentPath lub
\$config->addRepository<p>Aby uzyskaæ wiêcej szczegó³ów zapoznaj siê z
podrêcznikiem instalacyjnym";

$lang["DIFFREVS"] = "Ró¿nice pomiêdzy wersjami";
$lang["AND"] = "i";
$lang["REV"] = "Wersja";
$lang["LINE"] = "Linia";
$lang["SHOWENTIREFILE"] = "Poka¿ ca³y plik";
$lang["SHOWCOMPACT"] = "Poka¿ tylko fragmety w których zasz³y zmiany";

$lang["DIFFPREV"] = "Porównaj z poprzedni± wersj±";
$lang["BLAME"] = "Wk³ad pracy";

$lang["REVINFO"] = "Informacje o wersji";
$lang["GOYOUNGEST"] = "Przejd¼ do najnowszej wersji";
$lang["LASTMOD"] = "Ostatnia zmiana";
$lang["LOGMSG"] = "Wpis z dziennika zmian";
$lang["CHANGES"] = "Zmiany";
$lang["SHOWCHANGED"] = "Poka¿ zmienione pliki";
$lang["HIDECHANGED"] = "Ukryj zmienione pliki";
$lang["NEWFILES"] = "Nowe pliki";
$lang["CHANGEDFILES"] = "Zmienione pliki";
$lang["DELETEDFILES"] = "Usuniête pliki";
$lang["VIEWLOG"] = "Poka¿&nbsp;dziennik&nbsp;zmian";
$lang["PATH"] = "¦cie¿ka";
$lang["AUTHOR"] = "Autor";
$lang["AGE"] = "Wiek";
$lang["LOG"] = "Dziennik&nbsp;zmian";
$lang["CURDIR"] = "Aktualny katalog";
$lang["TARBALL"] = "Archiwum tar";

$lang["PREV"] = "Poprzednia strona";
$lang["NEXT"] = "Nastêpna strona";
$lang["SHOWALL"] = "Poka¿ wszyskie";

$lang["BADCMD"] = "B³±d podczas wykonywania polecenia";

$lang["POWERED"] = "Obs³ugiwane przez <a
href=\"http://websvn.tigris.org/\">WebSVN</a>";
$lang["PROJECTS"] = "Projekty&nbsp;Subversion";
$lang["SERVER"] = "Serwer Subversion";

$lang["SEARCHLOG"] = "Przeszukaj dziennik zmian";
$lang["CLEARLOG"] = "Usuñ rezulaty wyszukiwania";
$lang["MORERESULTS"] = "Znajd¼ wiêcej dopasowañ...";
$lang["NORESULTS"] = "¯aden wpis w dzinniku zmian nie pasuje do zapytania";
$lang["NOMORERESULTS"] = "Nie ma ju¿ wiêcej wpisów pasuj±cych do
zadanych kryterów";

$lang["RSSFEEDTITLE"] = "WebSVN RSS feed";
$lang["FILESMODIFIED"] = "zmienione pliki";
$lang["RSSFEED"] = "RSS feed";

$lang["LINENO"] = "Linia nr";
$lang["BLAMEFOR"] = "Wk³ad pracy dla wersji";

$lang["YEARS"] = "lat";
$lang["MONTHS"] = "miesiêcy";
$lang["WEEKS"] = "tygodni";
$lang["DAYS"] = "dni";
$lang["HOURS"] = "godzin";
$lang["MINUTES"] = "minut";

$lang["GO"] = "Przejd¼";

$lang["PATHCOMPARISON"] = "Porównywanie katalogów";
$lang["COMPAREPATHS"] = "Porównaj katalogi";
$lang["COMPAREREVS"] = "Porównaj wersje";
$lang["PROPCHANGES"] = "Zmiany w³a¶ciwo¶ci :";
$lang["CONVFROM"] = "Poni¿sze zestawienie pokazuje zmiany konieczne by
zaktualizowaæ katalog";
$lang["TO"] = "na";
$lang["REVCOMP"] = "Odwróæ porównanie";
$lang["COMPPATH"] = "Porównaj katalog:";
$lang["WITHPATH"] = "Z katalogiem:";
$lang["FILEDELETED"] = "Plik usuniêty";
$lang["FILEADDED"] = "Nowy plik";

// The following are defined by some languages to stop unwanted line
splitting
// in the template files.

$lang["NOBR"] = "";
$lang["ENDNOBR"] = "";

// $lang["NOBR"] = "<nobr>";
// $lang["ENDNOBR"] = "</nobr>";
