<?php

// WebSVN - Subversion repository viewing via the web using PHP
// Copyright (C) 2004 Tim Armes
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --
//
// english.inc
//
// English language strings

$lang["LOG"] = "Log";
$lang["DIFF"] = "Sammenlign";

$lang["NOREP"] = "Der er ikke angivet noget versionarkiv";
$lang["NOPATH"] = "Stien blev ikke fundet";
$lang["SUPPLYREP"] = "Konfigurer venligst stier til versionsarkiver i include/config.inc ved at bruge \$config->parentPath eller \$config->addRepository<p>. Se installationsguiden for nærmere detaljer.";

$lang["DIFFREVS"] = "Sammenlign revisionerne";
$lang["AND"] = "og";
$lang["REV"] = "Rev";
$lang["LINE"] = "Linje";
$lang["SHOWENTIREFILE"] = "Vis hele filen";
$lang["SHOWCOMPACT"] = "Vis kun områder med forskelle";

$lang["DIFFPREV"] = "Sammenlign med forrige";
$lang["BLAME"] = "Ændringsfordeling";

$lang["REVINFO"] = "Informationer om revision";
$lang["GOYOUNGEST"] = "Gå til nyeste revision";
$lang["LASTMOD"] = "Sidste ændring";
$lang["LOGMSG"] = "Logbesked";
$lang["CHANGES"] = "Ændringer";
$lang["SHOWCHANGED"] = "Vis ændrede filer";
$lang["HIDECHANGED"] = "Skjul ændrede filer";
$lang["NEWFILES"] = "Nye filer";
$lang["CHANGEDFILES"] = "Ændrede filer";
$lang["DELETEDFILES"] = "Slettede filer";
$lang["VIEWLOG"] = "Vis&nbsp;log";
$lang["PATH"] = "Sti";
$lang["AUTHOR"] = "Forfatter";
$lang["AGE"] = "Alder";
$lang["LOG"] = "Log";
$lang["CURDIR"] = "Nuværende mappe";
$lang["TARBALL"] = "Tar-pakke";

$lang["PREV"] = "Forrige";
$lang["NEXT"] = "Næste";
$lang["SHOWALL"] = "Vis alle";

$lang["BADCMD"] = "Fejl ved udførelse af kommandoen";

$lang["POWERED"] = "Leveret af <a href=\"http://websvn.tigris.org/\">WebSVN</a>";
$lang["PROJECTS"] = "Subversion-projekter";
$lang["SERVER"] = "Subversion-server";

$lang["SEARCHLOG"] = "Søg i logbeskeder efter";
$lang["CLEARLOG"] = "Ryd nuværende søgning";
$lang["MORERESULTS"] = "Vis flere resultater...";
$lang["NORESULTS"] = "Der er ingen logbeskeder, der passer på søgningen";
$lang["NOMORERESULTS"] = "Der er ikke flere logbeskeder, som svarer til søgningen";

$lang["RSSFEEDTITLE"] = "WebSVN RSS-feed"; 
$lang["FILESMODIFIED"] = "fil(er) ændret"; 
$lang["RSSFEED"] = "RSS-feed"; 

$lang["LINENO"] = "Linjenr.";
$lang["BLAMEFOR"] = "Ændringsfordeling for revision";

$lang["YEARS"] = "år";
$lang["MONTHS"] = "måneder";
$lang["WEEKS"] = "uger";
$lang["DAYS"] = "dage";
$lang["HOURS"] = "timer";
$lang["MINUTES"] = "minutter";

$lang["GO"] = "Gå til";

$lang["PATHCOMPARISON"] = "Sammenligning af stier";
$lang["COMPAREPATHS"] = "Sammenlign stier";
$lang["COMPAREREVS"] = "Sammenlign revisioner";
$lang["PROPCHANGES"] = "Ændringer i egenskaber:";
$lang["CONVFROM"] = "Denne sammenligning viser de ændringer, der skal til for at konvertere stien ";
$lang["TO"] = "til";
$lang["REVCOMP"] = "Omvendt sammenligning";
$lang["COMPPATH"] = "Sammenlign sti:";
$lang["WITHPATH"] = "med sti:";
$lang["FILEDELETED"] = "Fil slettet";
$lang["FILEADDED"] = "Ny fil";

// The following are defined by some languages to stop unwanted line splitting
// in the template files. 

$lang["NOBR"] = "";
$lang["ENDNOBR"] = "";

// $lang["NOBR"] = "<nobr>";
// $lang["ENDNOBR"] = "</nobr>";
